name: "Build Debian Live Minimal ISO"

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: "Tag name"
        required: true
        default: 'latest'

  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Get Date"
        run: |
          echo "DATESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV 

      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: "Build Image"
        run: |
          ./build.sh

      - name: "Publish"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ env.DATESTAMP }}"
          title: "Debian 12 Live Minimal ISO"
          files: |
            output/debian12-live-minimal-x86_64.iso
            output/packages.txt
